stages:
  - deploy

deploy:
  stage: deploy
  image: ${CI_REGISTRY}/project_dev/infra:latest
  script:
    - helm version
    - kubectl version --short
    - echo 'get credentials'
    - yc config set service-account-key $YC_TOKEN
    - yc managed-kubernetes cluster get-credentials test-cluster --external --force
    - echo 'Install Infra'
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm upgrade --install ingress-nginx-controller bitnami/nginx-ingress-controller --namespace ingress-nginx --create-namespace --wait
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus --create-namespace --wait
    - helm upgrade --install rabbitmq bitnami/rabbitmq --namespace rabbitmq  --create-namespace --wait
    - helm repo add appscode https://charts.appscode.com/stable/
    - helm repo update
    - helm install mongodb appscode/stash-mongodb --version 3.6.1-v1 --namespace mongodb  --create-namespace --wait
