stages:
  - deploy

deploy:
  stage: deploy
  image: ${CI_REGISTRY}/project_dev/infra:latest
  when: manual
  script:
    - helm version
    - kubectl version --short
    - echo 'get credentials'
    - yc config set service-account-key $YC_TOKEN
    - yc managed-kubernetes cluster get-credentials test-cluster --external --force
    - echo 'Install Infra'
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm upgrade --install ingress-nginx-controller bitnami/nginx-ingress-controller --namespace ingress-nginx --create-namespace --wait
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus --create-namespace --wait --values ./prometheus/values.yaml
    - helm upgrade --install rabbitmq bitnami/rabbitmq --namespace rabbitmq  --create-namespace --wait
    - helm repo add appscode https://charts.appscode.com/stable/
    - helm repo update
    - kubectl create ns mongodb || echo "NS was created earlier"
    - kubectl apply -f ./mongo -n mongodb
    - kubectl create ns prod || echo "NS was created earlier"
    - kubectl create ns stage || echo "NS was created earlier"
    - kubectl apply -f ./service-monitors/crawler-monitor-prod.yaml -n prod
    - kubectl apply -f ./service-monitors/crawler-monitor-stage.yaml -n stage
    - kubectl apply -f ./service-monitors/ui-monitor-prod.yaml -n prod
    - kubectl apply -f ./service-monitors/ui-monitor-stage.yaml -n stage
