apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crawler-monitor-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: crawler
  endpoints:
  - interval: 15s
    path: /
    port: main
