apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-monitor-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: ui
  endpoints:
  - interval: 15s
    path: /metrics
    port: main
